In [1]:
 import pandas as pd

In [2]:
d=pd.read_csv("Salary_Data.csv")
d

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [3]:
d.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [4]:
d.tail()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [6]:
# Convert categorical → numerical
df = pd.get_dummies(d, columns=['Education Level', 'Gender', 'Job Title'], drop_first=True)
df

,Age,Years of Experience,Salary,Education Level_Bachelor's Degree,Education Level_High School,Education Level_Master's,Education Level_Master's Degree,Education Level_PhD,Education Level_phD,Gender_Male,...,Job Title_Supply Chain Manager,Job Title_Technical Recruiter,Job Title_Technical Support Specialist,Job Title_Technical Writer,Job Title_Training Specialist,Job Title_UX Designer,Job Title_UX Researcher,Job Title_VP of Finance,Job Title_VP of Operations,Job Title_Web Developer
0,32.0,5.0,90000.0,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,28.0,3.0,65000.0,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,45.0,15.0,150000.0,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
3,36.0,7.0,60000.0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,52.0,20.0,200000.0,False,False,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6699,49.0,20.0,200000.0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
6700,32.0,3.0,50000.0,False,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
6701,30.0,4.0,55000.0,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6702,46.0,14.0,140000.0,False,False,False,True,False,False,True,...,False,False,False,False,False,False,False,False,False,False
6703,26.0,1.0,35000.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
d.info()

In [ ]:
d.columns[d.isna().any()]

In [ ]:
d["Education Level"].unique()

In [ ]:
d["Job Title"].unique()

In [ ]:
d["Job Title"].value_counts()

In [ ]:
d=d.drop(["Job Title"],axis=1)

In [ ]:
d

In [ ]:
d["Education Level"].value_counts()

In [ ]:
d=d.drop("Education Level",axis=1)
d

In [ ]:
d["Gender"].value_counts()

In [ ]:
s=pd.get_dummies(d["Gender"])

In [ ]:
d=pd.concat([d,s],axis="columns")

In [ ]:
d

In [ ]:
d=d.drop(["Gender"],axis="columns")
d

In [ ]:
d.isnull().sum()

In [ ]:
d.columns[d.isna().any()]

In [ ]:
d[['Age', 'Years of Experience', 'Salary']]=d[['Age', 'Years of Experience', 'Salary']].fillna(d[['Age', 'Years of Experience', 'Salary']].mean())

In [ ]:
d[['Age', 'Years of Experience', 'Salary']]

In [ ]:
d.columns[d.isna().any()]

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(d["Age"])
plt.show()

In [ ]:
plt.scatter(d["Years of Experience"],d["Salary"])
plt.show()

In [ ]:
d

In [ ]:
#feature engineering
x=d[["Years of Experience"]]
y=d["Salary"]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=42)

In [ ]:
x_train

In [ ]:
x_test

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr=LinearRegression()
lr.fit(x_train,y_train)

In [ ]:
y_pred=lr.predict(x_test)
y_pred

In [ ]:
y_test

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test,y_pred)

In [ ]:
lr.coef_

In [ ]:
lr.intercept_

In [ ]:
import numpy as np
i=np.array(2.5).reshape(-1,1)
a=lr.predict(i)
a