In [1]:
import pandas as pd

In [2]:
d=pd.read_csv(r"C:\Users\Live wire\Downloads\titanic.csv")
d

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
d=pd.read_csv("titanic.csv")
d

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
d.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
d.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
print("hello\nworld")

hello
world

In [8]:
d.columns[d.isna().any()]

Index(['Age', 'Cabin', 'Embarked'], dtype='object')

In [9]:
d['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [10]:
d['Embarked']=d['Embarked'].fillna(d['Embarked'].mode()[0])
d.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [11]:
d['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [12]:
e=pd.get_dummies(d["Embarked"])
e

         C      Q      S
0    False  False   True
1     True  False  False
2    False  False   True
3    False  False   True
4    False  False   True
..     ...    ...    ...
886  False  False   True
887  False  False   True
888  False  False   True
889   True  False  False
890  False   True  False

[891 rows x 3 columns]

In [13]:
d.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [14]:
d.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [15]:
d=d.drop(['Cabin', 'Embarked'],axis="columns")
d

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500

In [16]:
d["Age"]=d['Age'].fillna(d['Age'].median())
d['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [17]:
d.columns[d.isna().any()]

Index([], dtype='object')

In [18]:
d.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.361582,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.019697,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [19]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
dtypes: float64(2), int64(5), object(3)
memory usage: 69.7+ KB

In [20]:
s=pd.get_dummies(d['Sex'])
d=pd.concat([d,s],axis=1)
d=d.drop("Sex",axis="columns")
d

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,female,male
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,True,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,True,False
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,False,True
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,True,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",28.0,1,2,W./C. 6607,23.4500,True,False
889,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,False,True
890,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,False,True

In [21]:
d.head(10)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,female,male
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,True,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,True,False
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,False,True
5,6,0,3,"Moran, Mr. James",28.0,0,0,330877,8.4583,False,True
6,7,0,1,"McCarthy, Mr. Timothy J",54.0,0,0,17463,51.8625,False,True
7,8,0,3,"Palsson, Master. Gosta Leonard",2.0,3,1,349909,21.0750,False,True
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",27.0,0,2,347742,11.1333,True,False
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",14.0,1,0,237736,30.0708,True,False

In [22]:
d.tail(15)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,female,male
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",20.0,0,0,7534,9.8458,False,True
877,878,0,3,"Petroff, Mr. Nedelio",19.0,0,0,349212,7.8958,False,True
878,879,0,3,"Laleff, Mr. Kristo",28.0,0,0,349217,7.8958,False,True
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",56.0,0,1,11767,83.1583,True,False
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",25.0,0,1,230433,26.0000,True,False
881,882,0,3,"Markun, Mr. Johann",33.0,0,0,349257,7.8958,False,True
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",22.0,0,0,7552,10.5167,True,False
883,884,0,2,"Banfield, Mr. Frederick James",28.0,0,0,C.A./SOTON 34068,10.5000,False,True
884,885,0,3,"Sutehall, Mr. Henry Jr",25.0,0,0,SOTON/OQ 392076,7.0500,False,True
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",39.0,0,5,382652,29.1250,True,False
886,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,True,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",28.0,1,2,W./C. 6607,23.4500,True,False
889,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,False,True
890,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,False,True

In [23]:
de={"name":["nisha","lisa","bosha","vijay","hussain","pradheepa","gavaskar","thaniyarasu","lokesh","anusha"],
"course":["DS","AI","AI","DS","DS","DS","AI","DA","DS","ML"]}
de

{'name': ['nisha',
  'lisa',
  'bosha',
  'vijay',
  'hussain',
  'pradheepa',
  'gavaskar',
  'thaniyarasu',
  'lokesh',
  'anusha'],
 'course': ['DS', 'AI', 'AI', 'DS', 'DS', 'DS', 'AI', 'DA', 'DS', 'ML']}

In [24]:
df=pd.DataFrame(de)
df

          name course
0        nisha     DS
1         lisa     AI
2        bosha     AI
3        vijay     DS
4      hussain     DS
5    pradheepa     DS
6     gavaskar     AI
7  thaniyarasu     DA
8       lokesh     DS
9       anusha     ML

In [25]:
d[(d["PassengerId"]>25) & (d['Fare']>50)]

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,female,male
27,28,0,1,"Fortune, Mr. Charles Alexander",19.0,3,2,19950,263.0000,False,True
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",28.0,1,0,PC 17569,146.5208,True,False
34,35,0,1,"Meyer, Mr. Edgar Joseph",28.0,1,0,PC 17604,82.1708,False,True
35,36,0,1,"Holverson, Mr. Alexander Oskar",42.0,1,0,113789,52.0000,False,True
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",49.0,1,0,PC 17572,76.7292,True,False
...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",45.0,1,1,36928,164.8667,True,False
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",28.0,8,2,CA. 2343,69.5500,True,False
867,868,0,1,"Roebling, Mr. Washington Augustus II",31.0,0,0,PC 17590,50.4958,False,True
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",47.0,1,1,11751,52.5542,True,False
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",56.0,0,1,11767,83.1583,True,False

In [26]:
d

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,female,male
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,True,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,True,False
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,False,True
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,True,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",28.0,1,2,W./C. 6607,23.4500,True,False
889,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,False,True
890,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,False,True

In [27]:
d.sort_values("Fare")

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,female,male
271,272,1,3,"Tornquist, Mr. William Henry",25.0,0,0,LINE,0.0000,False,True
597,598,0,3,"Johnson, Mr. Alfred",49.0,0,0,LINE,0.0000,False,True
302,303,0,3,"Johnson, Mr. William Cahoone Jr",19.0,0,0,LINE,0.0000,False,True
633,634,0,1,"Parr, Mr. William Henry Marsh",28.0,0,0,112052,0.0000,False,True
277,278,0,2,"Parkes, Mr. Francis ""Frank""",28.0,0,0,239853,0.0000,False,True
...,...,...,...,...,...,...,...,...,...,...,...
438,439,0,1,"Fortune, Mr. Mark",64.0,1,4,19950,263.0000,False,True
341,342,1,1,"Fortune, Miss. Alice Elizabeth",24.0,3,2,19950,263.0000,True,False
737,738,1,1,"Lesurer, Mr. Gustave J",35.0,0,0,PC 17755,512.3292,False,True
258,259,1,1,"Ward, Miss. Anna",35.0,0,0,PC 17755,512.3292,True,False
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",36.0,0,1,PC 17755,512.3292,False,True

In [28]:
d.sort_values("Fare",ascending=False)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,female,male
258,259,1,1,"Ward, Miss. Anna",35.0,0,0,PC 17755,512.3292,True,False
737,738,1,1,"Lesurer, Mr. Gustave J",35.0,0,0,PC 17755,512.3292,False,True
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",36.0,0,1,PC 17755,512.3292,False,True
88,89,1,1,"Fortune, Miss. Mabel Helen",23.0,3,2,19950,263.0000,True,False
27,28,0,1,"Fortune, Mr. Charles Alexander",19.0,3,2,19950,263.0000,False,True
...,...,...,...,...,...,...,...,...,...,...,...
633,634,0,1,"Parr, Mr. William Henry Marsh",28.0,0,0,112052,0.0000,False,True
413,414,0,2,"Cunningham, Mr. Alfred Fleming",28.0,0,0,239853,0.0000,False,True
822,823,0,1,"Reuchlin, Jonkheer. John George",38.0,0,0,19972,0.0000,False,True
732,733,0,2,"Knight, Mr. Robert J",28.0,0,0,239855,0.0000,False,True
674,675,0,2,"Watson, Mr. Ennis Hastings",28.0,0,0,239856,0.0000,False,True

In [29]:
d['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [30]:
d['Survived'].value_counts(normalize=True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [31]:
d[d['female']& d["Survived"]]

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,female,male
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,True,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,True,False
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",27.0,0,2,347742,11.1333,True,False
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",14.0,1,0,237736,30.0708,True,False
...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",28.0,1,0,P/PP 3381,24.0000,True,False
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",15.0,0,0,2667,7.2250,True,False
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",56.0,0,1,11767,83.1583,True,False
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",25.0,0,1,230433,26.0000,True,False
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,True,False